# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DiodeTest.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_DiodeTest(object):
    def setupUi(self, Dialog_DiodeTest):
        Dialog_DiodeTest.setObjectName("Dialog_DiodeTest")
        Dialog_DiodeTest.resize(1030, 642)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Logos/logotrspisq.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog_DiodeTest.setWindowIcon(icon)
        self.tableWidget = QtWidgets.QTableWidget(Dialog_DiodeTest)
        self.tableWidget.setGeometry(QtCore.QRect(10, 11, 1011, 551))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.pushButton_Measure = QtWidgets.QPushButton(Dialog_DiodeTest)
        self.pushButton_Measure.setGeometry(QtCore.QRect(210, 590, 93, 28))
        self.pushButton_Measure.setObjectName("pushButton_Measure")
        self.pushButton_Save = QtWidgets.QPushButton(Dialog_DiodeTest)
        self.pushButton_Save.setGeometry(QtCore.QRect(310, 590, 93, 28))
        self.pushButton_Save.setObjectName("pushButton_Save")
        self.pushButton_Abort = QtWidgets.QPushButton(Dialog_DiodeTest)
        self.pushButton_Abort.setGeometry(QtCore.QRect(420, 590, 93, 28))
        self.pushButton_Abort.setObjectName("pushButton_Abort")
        self.pushButton_Back = QtWidgets.QPushButton(Dialog_DiodeTest)
        self.pushButton_Back.setGeometry(QtCore.QRect(530, 590, 93, 28))
        self.pushButton_Back.setObjectName("pushButton_Back")
        self.progressBar = QtWidgets.QProgressBar(Dialog_DiodeTest)
        self.progressBar.setGeometry(QtCore.QRect(630, 590, 401, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_Units = QtWidgets.QLabel(Dialog_DiodeTest)
        self.label_Units.setGeometry(QtCore.QRect(20, 590, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Units.setFont(font)
        self.label_Units.setObjectName("label_Units")
        self.comboBox = QtWidgets.QComboBox(Dialog_DiodeTest)
        self.comboBox.setGeometry(QtCore.QRect(80, 590, 111, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")

        self.retranslateUi(Dialog_DiodeTest)
        QtCore.QMetaObject.connectSlotsByName(Dialog_DiodeTest)

    def retranslateUi(self, Dialog_DiodeTest):
        _translate = QtCore.QCoreApplication.translate
        Dialog_DiodeTest.setWindowTitle(_translate("Dialog_DiodeTest", "Diode Test"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_DiodeTest", "S.No"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_DiodeTest", "Line X"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog_DiodeTest", "LineY"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog_DiodeTest", "Min"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog_DiodeTest", "Measured Value"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog_DiodeTest", "Max"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog_DiodeTest", "Units"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Dialog_DiodeTest", "Results"))
        self.pushButton_Measure.setText(_translate("Dialog_DiodeTest", "Measure"))
        self.pushButton_Save.setText(_translate("Dialog_DiodeTest", "Save"))
        self.pushButton_Abort.setText(_translate("Dialog_DiodeTest", "Abort"))
        self.pushButton_Back.setText(_translate("Dialog_DiodeTest", "Back"))
        self.label_Units.setText(_translate("Dialog_DiodeTest", "Units:"))
        self.comboBox.setItemText(0, _translate("Dialog_DiodeTest", "Ohms"))
